ARG FAASR_VERSION
FROM faasr/base-tidyverse:$FAASR_VERSION

# Get arguments
ARG FAASR_TAG
ARG FAASR_INSTALL_REPO

# Install FaaSr
RUN Rscript -e "args <- commandArgs(trailingOnly=TRUE); library(devtools); install_github(paste0(args[1],'@',args[2]),force=TRUE)" $FAASR_INSTALL_REPO $FAASR_TAG

RUN chmod -R 755 /action

WORKDIR /lambda_runtime

ENTRYPOINT ["/lambda_runtime/entry.sh"]

CMD ["lambda_function.handler"]
